### ISSUE TITLE
grid-middle not working

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1675-planet-website#1]
Hi Thomas,

I'm having difficulty with the grid-middle class, when I put it in my html and delete text-align: centre from my css, the elements don't stay centre-aligned. Have I liked something incorrectly perhaps?

Thank you!

@thomasjbradley

**Comment by thomasjbradley** [comment]
Where are you using it in your website?
And do you want it to be vertically aligned or horizontally aligned?

**Comment by kaybow** [comment]
I was trying to use it specifically on the h2 "moons", that stays centered in all screen sizes, and "venus" in xs size. Horizontally aligned.

**Comment by thomasjbradley** [comment]
Okay. The grid middle works on vertical alignment of the units, so it's not what you're looking for here.

For the `<h2>` on moons, try `text-center`.

For the "Venus" you'll have to do media queries and `text-align: center` because it isn't always centered.
